
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESS_TE = 25;
  public static final int MASMAS = 42;
  public static final int CHAR_LIT = 33;
  public static final int STRING_LITERAL = 34;
  public static final int POT = 49;
  public static final int MENOSMENOS = 43;
  public static final int ASIGNAR = 35;
  public static final int FIN_EXPR = 54;
  public static final int CHAR = 16;
  public static final int EMPTY = 13;
  public static final int ENTERO = 29;
  public static final int CASE = 7;
  public static final int RESTA = 45;
  public static final int EXPONENCIAL = 31;
  public static final int DOS_PUNTOS = 56;
  public static final int INT = 19;
  public static final int FINAL_PAREN = 39;
  public static final int SEPARADOR = 53;
  public static final int NOT = 52;
  public static final int AND = 51;
  public static final int FRACCION = 32;
  public static final int OR = 50;
  public static final int INICIO_BLOQUE = 40;
  public static final int BOOL = 18;
  public static final int DIV = 47;
  public static final int FINAL_INDICES = 37;
  public static final int INICIO_INDICES = 36;
  public static final int SUMA = 44;
  public static final int MAIN = 14;
  public static final int IF = 2;
  public static final int ID = 28;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 22;
  public static final int FINAL_BLOQUE = 41;
  public static final int GREATHER_TE = 27;
  public static final int TRUE = 20;
  public static final int error = 1;
  public static final int COMA = 55;
  public static final int MOD = 48;
  public static final int CIN = 11;
  public static final int BREAK = 9;
  public static final int SWITCH = 6;
  public static final int ELSE = 3;
  public static final int COUT = 12;
  public static final int N_EQUAL = 23;
  public static final int WHILE = 5;
  public static final int DEFAULT = 8;
  public static final int FLOAT = 17;
  public static final int GREATHER_T = 26;
  public static final int MULTI = 46;
  public static final int STRING = 15;
  public static final int FALSE = 21;
  public static final int LESS_T = 24;
  public static final int FLOTANTE = 30;
  public static final int DO = 4;
  public static final int INICIO_PAREN = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "RETURN",
  "CIN",
  "COUT",
  "EMPTY",
  "MAIN",
  "STRING",
  "CHAR",
  "FLOAT",
  "BOOL",
  "INT",
  "TRUE",
  "FALSE",
  "EQUAL",
  "N_EQUAL",
  "LESS_T",
  "LESS_TE",
  "GREATHER_T",
  "GREATHER_TE",
  "ID",
  "ENTERO",
  "FLOTANTE",
  "EXPONENCIAL",
  "FRACCION",
  "CHAR_LIT",
  "STRING_LITERAL",
  "ASIGNAR",
  "INICIO_INDICES",
  "FINAL_INDICES",
  "INICIO_PAREN",
  "FINAL_PAREN",
  "INICIO_BLOQUE",
  "FINAL_BLOQUE",
  "MASMAS",
  "MENOSMENOS",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIV",
  "MOD",
  "POT",
  "OR",
  "AND",
  "NOT",
  "SEPARADOR",
  "FIN_EXPR",
  "COMA",
  "DOS_PUNTOS"
  };
}

